---
- hosts: all
  tasks:
    - name: Verify that a regular snap package can be installed
      become: true
      community.general.snap:
        name: standard-notes
        state: present
      ignore_errors: true

    - name: Verify that another regular snap package can be installed
      become: true
      community.general.snap:
        name: gimp
        state: present
      ignore_errors: true

    - name: Verify that a classic snap can be installed
      become: true
      community.general.snap:
        name: android-studio
        state: present
        classic: true
      ignore_errors: true

    - name: Check if attempting to install a classic snap twice fixes the issue
      become: true
      community.general.snap:
        name: android-studio
        state: present
        classic: true
      ignore_errors: true

    - name: Verify that a classic snap can be installed (without attempting twice)
      become: true
      community.general.snap:
        name: code
        classic: true
        state: present
